# Generated by Django 4.1.4 on 2023-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_contact_info_post_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='job_description',
        ),
        migrations.AddField(
            model_name='post',
            name='short_job_description',
            field=models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s", max_length=100),
            preserve_default=False,
        ),
    ]
