# Generated by Django 4.1.4 on 2023-03-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='answer',
            new_name='Learning_disabilities',
        ),
    ]
