# Generated by Django 4.1.4 on 2023-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_answer_post_learning_disabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Cerebral_palsy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Hearing_loss',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Intellectual_disability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
