# Generated by Django 4.1.4 on 2023-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_cerebral_palsy_post_hearing_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Diabetes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Dyslexia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Neurological_disorder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Parkinsons_disease',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Physical_disability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Spinal_cord_injury',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Stroke',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Vision_impairment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
