# Generated by Django 4.1.4 on 2023-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_intellectual_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_requirements',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
